### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by memnos** [KBlixt/Trailer-Downloader#2]
Hello,
i have this error running the script.
Any idea how to solve?
Tnx

https://paste2.org/ztpNfPtv

BTW is there the possibility to choose the language of the trailer?

**Comment by KBlixt** [comment]
hey, sorry for not seeing this until now.

unsure about what the issue is here and I'm not going to try to fix it. go visit my movie-extra-downloader repository it is much more robust with much more features.

no, but have a look into the other repository. there you can customize the search to include other wanted terms such as what language they are in. this wont guarantee that language however, but it's more likely. alternatively you can choose google movie trailers since those are generally speaking region specific and you'll get your own language if they have released a specific trailer for your region.

feel free to ask any questions about that repository over there.
